[package]
name = "altjh/classic-click-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Net = "vorlias/net@3.0.1"
FormatNumber = "kumarion/formatnumber@0.0.1"
Iris = "sirmallard/iris@2.5.0"

[server-dependencies]
ProfileService = "grilme99/profileservice@1.0.0"
Cmdr = "evaera/cmdr@1.12.0"